### ISSUE TITLE
Add a file in c, which shows a multiplication table .

### ISSUE THREAD

**Issue by rishabh1911007** [SAMYAK99/CS-180#760] opened 2022-10-15 20:09 UTC
Could you please assign me for this issue.

**Comment by rishabh1911007** [comment] 2022-10-15 20:57
#Hacktoberfest2022

**Comment by keshavsolankii** [comment] 2022-10-22 14:54
Sir, can you assign me this issue?

**Comment by silky-modi22** [comment] 2022-10-23 18:30
can you please assign this issue to me!

**Closed** 2022-10-27 15:47 UTC

**Comment by silky-modi22** [comment] 2022-10-27 16:22
Why you closed my pr . What you exactly want . Please mention it I'll try
to add it.

**Comment by silky-modi22** [comment] 2022-10-27 16:28
Ok, it's fine because it is the issue is solved.
